### ISSUE TITLE
Full Backup with Hebrew Characters fails

### ISSUE THREAD

**Issue by barronen1** [peno64/script.ezmaintenanceplus#2]
Can you make it possible to do a Kodi full backup without errors when I’m trying to back up with favorite with Hebrew string characters in my favorites names?

**Comment by peno64** [comment]
Since I dont have Hebrew that is difficult. At leest you should post a kodi log file with debugging on bit even then no guarantees.

**Comment by barronen1** [comment]
![Uploading image.jpg…]()

**Comment by barronen1** [comment]
Thank you for your fast answer!

I’ve ran now the full backup again (with Favorites page configured with Hebrew names), and this is the end of the log file attached from camera.  

How do I turn on debugging, and send you the full log as file?

**Comment by barronen1** [comment]
My favorites page for example:


![](https://i.imgur.com/wi9OtkF.jpg)

**Comment by peno64** [comment]
could you provide me your favourites.xml file?
It's in the userdata folder

**Comment by barronen1** [comment]
[favourites.xml.zip](https://github.com/peno64/script.ezmaintenanceplus/files/10311094/favourites.xml.zip)

**Comment by barronen1** [comment]
Attached. (unzip)

[favourites.xml.zip](https://github.com/peno64/script.ezmaintenanceplus/files/10311096/favourites.xml.zip)

**Comment by peno64** [comment]
I can simulate your issue with your favourites file. 
Now trying to figure out what the original developer wanted to accomplish in that code and see if there is a work-around for it.

**Comment by barronen1** [comment]
You're not the original developer of EZ Maintenance+?

**Comment by peno64** [comment]
No I am not. The addon wasn't maintained anymore when kodi 19 came out and I modified it such that it also works with python 3. It's originally from here: https://github.com/aenemapy/aenemapyrepo/tree/master/script.ezmaintenanceplus

Anyway, I have a fix for it. It has to do with your Hebrew characters in the favourites files and the addon that couldn't handle that. 

I will release the fix in a couple of hours.

**Comment by peno64** [comment]
The update is online via the repo.
To force kodi to check if there are updates, do the following:
Kodi, press "My Addons", In that menu, press left arrow, choose "Check for Updates"

**Comment by barronen1** [comment]
I've tested and it worked.
Thank you!

**Comment by barronen1** [comment]
I have another question,
There are 2 options for backup: addons and full

But from what I’ve tested, Full backup does backup only add-ons (and also favorites page), but not the entire Kodi as a whole, for example - Kodi internal settings (not add ons). 

Does it supposed to?

**Comment by peno64** [comment]
I have no idea. I would have to look into the code.

But if I remember well, there is in the standard kodi repo also a backup/restore program

**Comment by barronen1** [comment]
Yes I’ve also tried this program, but I didn’t like it and it isn’t working very good,

if you could check if it’s possible to backup also Kodi settings in the full backup it will be great!

**Comment by peno64** [comment]
As far as I can see full backup backups everything.
I also checked this by unziping the backup file and then compare it to the kodi folder.
It contains all files

**Comment by barronen1** [comment]
True,
I also checked the files. the files for all Kodi internal settings is - guisettings.xml

But I don't know why but, when I restore from the zip file created by Full backup, or by enabling Wizard and putting the url to the same zip file from backup file - It restores all Add-ons and their settings, and doesn't do anything with guisettings.xml file fom the zip file.

And Kodi stays the same in terms of Kodi settings.

**Comment by peno64** [comment]
Maybe then restore isnt restoring it.
Note that I can imagine that restoring this can be a problem because for example restoren a kodi guisettings file from Android on a kodi on Windows could be problematic maybe because not all settings are available or should even be different between kodi on different platforms...

**Comment by barronen1** [comment]
I see. we'll that's good enough even without Kodi settings
Thanks for the help!

**Comment by barronen1** [comment]
By the way, is there a tutorial for how to properly use the Wizard feature?

**Comment by peno64** [comment]
As far as I know, nope
