### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by Arthur1967** [peno64/script.ezmaintenanceplus#4]
I just tried to install the new version on 19.5 and it gave an error. The old version works good. I'll have to look at it when I get more time just letting you know 19.5 on the fire stick. I'll do it later on tonight.

**Comment by peno64** [comment]
Please try again. I was just releasing a new version and there was a small error in it. It is fixed in the meantime: https://github.com/peno64/script.ezmaintenanceplus/releases

**Comment by Arthur1967** [comment]
Thank you for your help. I got it.
