### ISSUE TITLE
Sauvegarde Backup FTP

### ISSUE THREAD

**Issue by KodiPerso** [peno64/script.ezmaintenanceplus#5]
Bonjour
J'utilise EZ Maintenance+ que j'adore pour la sauvegarde de mon KODI.
J'aimerais savoir comment effectuer les sauvegarde sur mon serveur FTP.
J'ai essayer de modifier le fichier setting.xml mes je reçois une erreur.
pouvez vous me dire ou ajouter le lien de mon serveur ftp://user:password@ftp.clusterxx.hosting.ovh.net/www/xxxx/xxxx
Merci beaucoup es bravo pour cette addon pour moi indispensable.

**Comment by peno64** [comment]
As far as I know it is not possible to change a file path to an ftp:// path.
ftp is a special protocol and to send something via ftp it must be initiated from the side where the file goes to and not from the side where the file is coming from. So this is just not possible.

**Comment by KodiPerso** [comment]
Merci Beaucoup pour votre retour
